title: Jack
description: Jack blog
author: Jack
avatar: /logo.png
email: dhkdndksk@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jaegeunha94.github.io/" # the base hostname & protocol for your site

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
